title: MATRIX Dashboards
subtitle: "Decision and Collaboration Dashboards: A Practical Manual"
name: "Wiktor Gustafsson"
repository: "sva-se/matrix-dashboards"
url: "https://sva-se.github.io"
baseurl: "/MATRIX-dashboards"
description: An inventory of dashboard development for One Health disease surveillance.
remote_theme: pmarsceill/just-the-docs
permalink: pretty
logo: "assets/matrix_logo.png"

search_enabled: true

aux_links:
  "Dashboard Information Centre on GitHub":
    - "//github.com/sva-se/matrix-dashboards"
  "OHEJP MATRIX Homepage":
    - "//onehealthejp.eu/jip-matrix/"
aux_links_new_tab: true

nav_external_links:
  - title: Dashboard Information Centre on GitHub
    url: https://github.com/sva-se/matrix-dashboards
  - title: OHEJP MATRIX Homepage
    url: https://onehealthejp.eu/jip-matrix/

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d at %H-%M-%S"

heading_anchors: true

ga_tracking: G-M7ZMDX6LH7

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
